version: '3.9'

services:

#  apache:
#    build:
#      context: .
#      dockerfile: ./.docker/apache/Dockerfile
#    container_name: apache
#    restart: unless-stopped
#    ports:
#      - "82:80"
#    volumes:
#      - .:/var/www
#      - ./.docker/apache/config/apache.conf:/usr/local/apache2/conf.d/apache.conf
#      - ./.docker/apache/logs/:/usr/local/apache2/logs
#    depends_on:
#      - php
#    networks:
#      - apache

#  nginx:
#    build:
#      context: .
#      dockerfile: ./.docker/nginx/Dockerfile
#    container_name: nginx
#    restart: unless-stopped
#    ports:
#      - "83:80"
#    volumes:
#      - .:/var/www
#      - ./.docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
#      - ./.docker/nginx/logs/:/var/log/nginx
#    depends_on:
#      - php
#    networks:
#      - nginx

  php:
    build:
      context: .
#      dockerfile: ./.docker/php/php_5.4_legacy_diol/Dockerfile
#      dockerfile: ./.docker/php/php_5.4/Dockerfile
#      dockerfile: ./.docker/php/php_7.2/Dockerfile
#      dockerfile: ./.docker/php/php_7.4/Dockerfile
#      dockerfile: ./.docker/php/php_8.0/Dockerfile
    container_name: php
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
      - ./.docker/php/log/xdebug-log:/tmp
      - ./.docker/php/log:/var/log
    networks:
      - apache
      - nginx

  db:
    build:
      context: .
#      dockerfile: ./.docker/db/mysql_5.6/Dockerfile
#      dockerfile: ./.docker/db/mysql_5.7/Dockerfile
#      dockerfile: ./.docker/db/mysql_8.0/Dockerfile
#      dockerfile: ./.docker/db/mariadb_10.3/Dockerfile
    container_name: db
    restart: unless-stopped
    ports:
      - "3306:3306"
    volumes:
#      - ./.docker/db/mysql_5.6/data:/var/lib/mysql
#      - ./.docker/db/mysql_5.7/data:/var/lib/mysql
#      - ./.docker/db/mysql_8.0/data:/var/lib/mysql
#      - ./.docker/db/mariadb_10.3/data:/var/lib/mysql
#      - ./.docker/dump_db/:/docker-entrypoint-initdb.d/    # dump autoload - я не пользуюсь, гружу вручную
      - .:/var/www
    environment:
      - MYSQL_HOST=127.0.0.1
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=shop
    command: --default-authentication-plugin=mysql_native_password --net_buffer_length=1000000 --max_allowed_packet=1000000000
    networks:
      - apache
      - nginx
      - web-phpmyadmin

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma
    restart: unless-stopped
    environment:
      - PMA_ARBITRARY=1
    ports:
      - "8001:80"
    links:
      - db:db
    depends_on:
      - db
    networks:
      - web-phpmyadmin

# redis:
#    image: redis:alpine
#    container_name: redis
#    ports:
#      - "6379:6379"
#    restart: unless-stopped
#    networks:
#      - apache
#      - nginx

#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.3@sha256:0efc3a054ae97ad00cccc33b9ef79ec022970b2a9949893db4ef199edcdca2ce
#    container_name: elastic
#    ports:
#      - "9200:9200"
#    restart: unless-stopped
#    environment:
#      - discovery.type=single-node
#      - bootstrap.memory_lock=true
#    networks:
#      - apache
#      - nginx

networks:
  apache:
    driver: bridge
  nginx:
    driver: bridge
  web-phpmyadmin:
    driver: bridge