version: '3.7'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    restart: always


  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - 82:82
      - 443:443
    volumes:
      - .:/var/www
      - ./.docker/nginx_config/default.conf:/etc/nginx/conf.d/default.conf
      - ./.docker/nginx_logs/:/var/log/nginx
    depends_on:
      - php


  php:                                   # select version php
    #build: ./.docker/php_5.4/
    #build: ./.docker/php_7.2/
    #build: ./.docker/php_7.4
    container_name: php
    restart: always
    ports:
      - 9000:9000
    volumes:
      - .:/var/www
    environment:
      - PHP_DEBUGGER=xdebug
      # - XDEBUG_ENABLE=true
      - PHP_IDE_CONFIG=serverName=nginx

  db:                                    # select database
    #build: ./.docker/mariadb_10.3/
    #build: ./.docker/mysql_5.6/
    #build: ./.docker/mysql_5.7/         # 5.7 чё-то не работает, хз почему
    container_name: db
    restart: always
    ports:
      - 3306:3306
    volumes:
      #- ./.docker/dump_db/:/docker-entrypoint-initdb.d/    # dump autoload
      #- ./.docker/mariadb_10.3/data:/var/lib/mysql
      #- ./.docker/mysql_5.6/data:/var/lib/mysql
      #- ./.docker/mysql_5.7/data:/var/lib/mysql
      - .:/var/www
    environment:
      - MYSQL_HOST=127.0.0.1
      - MYSQL_PORT=3306
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=shop
    command: --default-authentication-plugin=mysql_native_password


  phpmyadmin:
    container_name: pma
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8001:80
    links:
      - db:db
    depends_on:
      - db
